on:
  workflow_dispatch:
    # schedule:
      # - cron: 0 9 */7 * *
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release And Upload assets

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.2'
      - name: Build Web
        run: |
          cd frontend && npm install && npm run build:pro
        env:
          NODE_OPTIONS: --max-old-space-size=8192
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'
      - name: Build Release
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
          workdir: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}
      - name: Upload Assets
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          # draft: true
          body: |
            # 一、安装和升级

            ## 1.1 一键安装
            ```sh
            curl -sSL https://raw.githubusercontent.com/gcsong023/wrt_installer/wrt_1panel/quick_start.sh -o quick_start.sh && bash quick_start.sh
            ```

            ## 1.2 在线升级

            登录 1Panel Web 控制台，在页面右下角点击 **【检查更新】** 进行在线升级。(未适配)

            >更多信息请查阅在线文档：https://1panel.cn/docs/

            # 二、更新日志

          files: |
            dist/*.tar.gz
            dist/checksums.txt
